// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with safe fallbacks for no-code deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "placeholder-key";
const SITE_URL = import.meta.env.VITE_SITE_URL || "https://growthscale-home-landing.vercel.app";

// Determine the redirect URL based on environment - UNIFICADO
const getRedirectUrl = () => {
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    const currentPort = window.location.port || '3000';
    console.log('🔗 Configurando redirect URL para porta:', currentPort);
    return `http://localhost:${currentPort}/auth/callback`;
  }
  return `${SITE_URL}/auth/callback`;
};

console.log('🔧 Configuração do Supabase Client:');
console.log('📍 URL:', SUPABASE_URL);
console.log('🔑 Chave:', SUPABASE_PUBLISHABLE_KEY ? 'Configurada' : 'Não configurada');
console.log('🌐 Site URL:', SITE_URL);
console.log('🔄 Redirect URL:', getRedirectUrl());

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'supabase.auth.token',
  }
});
