// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with safe fallbacks for no-code deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "placeholder-key";

// Determine the redirect URL based on environment
const getRedirectUrl = () => {
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    const currentPort = window.location.port || '3000'; // Use 3000 como fallback
    console.log('🔗 Configurando redirect URL para porta:', currentPort);
    return `http://localhost:${currentPort}/auth/callback`;
  }
  return 'https://growthscale-home-landing-edpw6muof.vercel.app/auth/callback';
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});
